- name: install nginx
  yum:
    name:
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: create dir www
  file:
    path: /var/www/html/
    state: directory
  become: yes 

- name: copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html


